input {
  tcp {
    port => 5000
    codec => json_lines
    host => "0.0.0.0"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
  }
  
  file {
    path => "/var/log/logstash/spring-logs-%{+YYYY-MM-dd}.log"
  }
  stdout { codec => rubydebug }
}